const categoryProducts = [
	{
		_id: 10001,
		title: 'Monogram Cotton Overshirt',
		price: '11,700.00',
		size: ['s', 'm', 'l', 'xl'],
		image: 'https://i.ibb.co/GtyHgvB/louis-vuitton-monogram-cotton-overshirt-HPB45-W026906-PM2-Front-view.webp',
		subcategory: 'ready-to-wear',
		category: 'men',
		color: ['red', 'black', 'blue'],
		quantity: '14',
	},

	{
		_id: 10002,
		title: 'LV x YK Infinity Dots Knitted Dress',
		price: '10,100.00',
		category: 'women',
		image: 'https://i.ibb.co/DpSMXRr/louis-vuitton-lv-x-yk-infinity-dots-knitted-dress-FOKD16-YC1900-PM2-Front-view.webp',
		subcategory: 'dresses',
		color: ['red', 'black', 'blue'],
		size: ['s', 'm', 'l', 'xl'],
		quantity: '14',
	},

	{
		_id: 10003,
		title: 'Toiletry Pouch On Chain',
		price: '8,200.00',
		Materials: 'Monogram',
		category: 'leatherGoods',
		image: 'https://i.ibb.co/NKkh0Px/louis-vuitton-toiletry-pouch-on-chain-M81412-PM2-Front-view.webp',
		subcategory: 'wallets-for-women',
		color: ['red', 'black', 'blue'],
		size: ['s', 'm', 'l', 'xl'],
		quantity: '14',
	},
	{
		_id: 10004,
		title: 'LV Futura Ring',
		price: '2,150.00',
		image: 'https://i.ibb.co/1MTqYYF/louis-vuitton-lv-futura-ring-MP355-S-PM2-Front-view.webp',
		category: 'jewelry',
		subcategory: 'rings',
		color: ['red', 'black', 'blue'],
		size: ['s', 'm', 'l', 'xl'],
		quantity: '14',
	},
	{
		_id: 10001,
		title: 'Monogram Cotton Overshirt',
		price: '11,700.00',
		size: ['s', 'm', 'l', 'xl'],
		image: 'https://i.ibb.co/GtyHgvB/louis-vuitton-monogram-cotton-overshirt-HPB45-W026906-PM2-Front-view.webp',
		subcategory: 'ready-to-wear',
		category: 'men',
		color: ['red', 'black', 'blue'],
		quantity: '14',
	},

	{
		_id: 10002,
		title: 'LV x YK Infinity Dots Knitted Dress',
		price: '10,100.00',
		category: 'women',
		image: 'https://i.ibb.co/DpSMXRr/louis-vuitton-lv-x-yk-infinity-dots-knitted-dress-FOKD16-YC1900-PM2-Front-view.webp',
		subcategory: 'dresses',
		color: ['red', 'black', 'blue'],
		size: ['s', 'm', 'l', 'xl'],
		quantity: '14',
	},

	{
		_id: 10003,
		title: 'Toiletry Pouch On Chain',
		price: '8,200.00',
		Materials: 'Monogram',
		category: 'leatherGoods',
		image: 'https://i.ibb.co/NKkh0Px/louis-vuitton-toiletry-pouch-on-chain-M81412-PM2-Front-view.webp',
		subcategory: 'wallets-for-women',
		color: ['red', 'black', 'blue'],
		size: ['s', 'm', 'l', 'xl'],
		quantity: '14',
	},
	{
		_id: 10004,
		title: 'LV Futura Ring',
		price: '2,150.00',
		image: 'https://i.ibb.co/1MTqYYF/louis-vuitton-lv-futura-ring-MP355-S-PM2-Front-view.webp',
		category: 'jewelry',
		subcategory: 'rings',
		color: ['red', 'black', 'blue'],
		size: ['s', 'm', 'l', 'xl'],
		quantity: '14',
	},
];

export default categoryProducts;
