export const data = [
  {
    title: "Keepall Bandoulière 25",
    price: "12,200.00",
    image:
      "https://i.ibb.co/NpBmHW0/louis-vuitton-keepall-bandouli-re-25-M22527-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },

  {
    title: "Steamer Wearable Wallet",
    price: "10,500.00",
    image:
      "https://i.ibb.co/hsfvt92/louis-vuitton-steamer-wearable-wallet-M22637-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },

  {
    title: "Discovery Bumbag",
    price: "10,500.00",
    image:
      "https://i.ibb.co/N704r5h/louis-vuitton-discovery-bumbag-M22576-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "City Keepall",
    price: "12,700.00",
    image:
      "https://i.ibb.co/t856hPN/louis-vuitton-city-keepall-M22486-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Takeoff Slingbag",
    price: "11,300.00",
    image:
      "https://i.ibb.co/cFMFGKR/louis-vuitton-takeoff-slingbag-M22665-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Mini Soft Trunk",
    price: "15,000.00",
    image:
      "https://i.ibb.co/Yd57CV5/louis-vuitton-mini-soft-trunk-M44735-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Christopher MM",
    price: "15,500.00",
    image:
      "https://i.ibb.co/hHZKtgw/louis-vuitton-christopher-mm-M45419-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Keepall Bandoulière 50",
    price: "15,900.00",
    image:
      "https://i.ibb.co/wgP4fYr/louis-vuitton-keepall-bandouli-re-50-M22570-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Meteor Travel Bag 50",
    price: "21,600.00",
    image:
      "https://i.ibb.co/4YnWs4v/louis-vuitton-meteor-travel-bag-50-M22634-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Porte-Documents Voyage PM",
    price: "9,300.00",
    image:
      "https://i.ibb.co/PTZXYYc/louis-vuitton-porte-documents-voyage-pm-damier-graphite-bags-N41478-PM2-Front-view.webp",
    category: "men",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Cotton Overshirt",
    price: "11,700.00",
    size: ["s", "m", "MO", "xl"],
    image:
      "https://i.ibb.co/GtyHgvB/louis-vuitton-monogram-cotton-overshirt-HPB45-W026906-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Classic Cotton T-Shirt",
    price: "2,650.00",
    size: ["s", "m", "MO", "xl"],
    image:
      "https://i.ibb.co/CQcJPjw/louis-vuitton-classic-cotton-t-shirt-HAY50-WJC8815-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Pointelle Cotton Short-Sleeved Shirt",
    price: "7,350.00",
    size: ["s", "m", "MO", "xl"],
    image:
      "https://i.ibb.co/rZ1pHkK/louis-vuitton-monogram-pointelle-cotton-short-sleeved-shirt-HPN31-WY34001-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Embroidered Beads Cotton T-Shirt",
    price: "6,050.00",
    size: ["s", "m", "MO", "xl"],
    image:
      "https://i.ibb.co/mC5Rq0x/louis-vuitton-embroidered-beads-cotton-t-shirt-HPY35-WNPG002-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Mini Monogram Silk Blend Short-Sleeved Shirt",
    price: "6,700.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/wMBnY65/louis-vuitton-mini-monogram-silk-blend-short-sleeved-shirt-HPS51-WZO6900-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Long-Sleeved Cotton Shirt",
    price: "4,850.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/9qZKJJX/louis-vuitton-long-sleeved-cotton-shirt-HPS52-WZJ9001-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "CLASSIC SHORT SLEEVE PIQUE POLO",
    price: "2,900.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/mTGNgNK/louis-vuitton-classic-short-sleeve-pique-polo-HAJR32-JEA653-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Convertible Ripstop Shirt",
    price: "11,700.00",
    size: "50",
    image:
      "https://i.ibb.co/8XjB0JQ/louis-vuitton-convertible-ripstop-shirt-HPB01-WY90900-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Embroidered Signature Short-Sleeved Cotton Crewneck",
    price: "4,700.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/xjHt0ZF/louis-vuitton-embroidered-signature-short-sleeved-cotton-crewneck-HNN42-WOY8-R31-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Mink Gilet",
    price: "78,500.00",
    size: "50",
    image:
      "https://i.ibb.co/jfsRHKy/louis-vuitton-monogram-mink-gilet-HPL12-WAI9002-PM2-Front-view.webp",
    category: "ready-to-wear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Signature Polo With Embroidery",
    price: "3,850.00",
    size: ["XS", "SO", "MO", "LO", "XL", "3L"],
    image:
      "https://i.ibb.co/rQ3ZvH6/louis-vuitton-signature-polo-with-embroidery-HNY58-WJ64900-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "CLASSIC S-S PIQUE POLO",
    price: "2,900.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/qrVc34n/louis-vuitton-classic-s-s-pique-polo-HAJR32-JEA740-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Sporty V-Neck T-Shirt",
    price: "5,000.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/XYSxzWh/louis-vuitton-monogram-sporty-v-neck-t-shirt-HOY67-WVV4900-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Louis Vuitton Vintage Cycling Polo",
    price: "6,250.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/K9HGgRM/louis-vuitton-louis-vuitton-vintage-cycling-polo-HNN61-WF96602-PM2-Front-view.webp",
    category: "polos",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV House Printed T-Shirt",
    price: "3,750.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/MkGJJrG/louis-vuitton-lv-house-printed-t-shirt-HOY01-WNPG002-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Concert Print Tshirt",
    price: "3,750.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/GVY0F38/louis-vuitton-lv-concert-print-tshirt-HOY10-WNPG900-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Graphic Mesh Long-Sleeved T-Shirt",
    price: "5,300.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/cYDWwcy/louis-vuitton-lv-graphic-mesh-long-sleeved-t-shirt-HNY67-WP46001-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Gradient Cotton T-Shirt",
    price: "4,850.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/XkB2BTw/louis-vuitton-monogram-gradient-cotton-t-shirt-HKY46-WNPG332-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Courbet Painting Printed T-Shirt",
    price: "3,700.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/rZCTQv1/louis-vuitton-courbet-painting-printed-t-shirt-HNY62-WNPGMU1-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV 1854 Graphic Knit T-Shirt",
    price: "4,950.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/v313rzX/louis-vuitton-lv-1854-graphic-knit-t-shirt-HNN78-WZTD900-PM2-Front-view.webp",
    category: "t-shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  // women
  {
    title: "Victorine Wallet",
    price: "2,550.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/60B9nrv/louis-vuitton-victorine-wallet-M62360-PM2-Front-view.webp",
    category: "wallets-for-Women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Rosalie Coin Purse",
    price: "1,800.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/m9C8Wz7/louis-vuitton-rosalie-coin-purse-M62361-PM2-Front-view.webp",
    category: "wallets-for-Women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Rosalie Coin Purse",
    price: "2,150.00",
    Materials: "Monogram Empreinte Leather",
    image:
      "https://i.ibb.co/Byd736s/louis-vuitton-rosalie-coin-purse-M81455-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Key Pouch",
    price: "1,450.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/g67zrQd/louis-vuitton-key-pouch-M62650-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Sarah Wallet",
    price: "3,400.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/0VKVZjH/louis-vuitton-sarah-wallet-M80726-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Zippy Wallet",
    price: "3,450.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/2NnfVpF/louis-vuitton-zippy-wallet-M42616-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Emilie Wallet",
    price: "2,600.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/q00sr97/louis-vuitton-emilie-wallet-M60697-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Toiletry Pouch On Chain",
    price: "8,200.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/NKkh0Px/louis-vuitton-toiletry-pouch-on-chain-M81412-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Mini Pochette Accessoires",
    price: "3,850.00",
    Materials: "Bicolor Monogram Empreinte Leather",
    image:
      "https://i.ibb.co/JmD36B0/louis-vuitton-mini-pochette-accessoires-M80732-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Twist Belt Chain Pouch",
    price: "9,050.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/GR1YL6T/louis-vuitton-twist-belt-chain-pouch-M68750-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  
  {
    title: "Macro Tweed Side-Tie Dress",
    price: "25,600.00",
    Size: "36",
    image:
      "https://i.ibb.co/bzBhjyT/louis-vuitton-macro-tweed-side-tie-dress-FORO48094205-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Oversized Belt Denim Utility Dress",
    price: "11,000.00",
    Size: "36",
    image:
      "https://i.ibb.co/jhnsjPm/louis-vuitton-oversized-belt-denim-utility-dress-FORO67-CKJ650-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Chain Motif Lace Shirt Dress",
    price: "21,500.00",
    Size: "36",
    image:
      "https://i.ibb.co/XZ5Bj0L/louis-vuitton-chain-motif-lace-shirt-dress-FPDB01-VFC000-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Waves Dress",
    price: "29,500.00",
    Size: "36",
    image:
      "https://i.ibb.co/nPV28L4/louis-vuitton-monogram-waves-dress-FPDB04-Z31900-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Chain Print Floor-Length Tank Dress",
    price: "26,500.00",
    Size: "36",
    image:
      "https://i.ibb.co/3zH8WHw/louis-vuitton-chain-print-floor-length-tank-dress-FODX34-X98990-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Infinity Dots Knitted Dress",
    price: "10,100.00",
    Size: "36",
    image:
      "https://i.ibb.co/DpSMXRr/louis-vuitton-lv-x-yk-infinity-dots-knitted-dress-FOKD16-YC1900-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Oversized Zipper Pleated Dress",
    price: "23,900.00",
    Size: "36",
    image:
      "https://i.ibb.co/QXFx2nG/louis-vuitton-oversized-zipper-pleated-dress-FORO90-VIB002-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Electric Blue Silk Georgette Midi Dress",
    price: "24,500.00",
    Size: "36",
    image:
      "https://i.ibb.co/fYB1QV7/louis-vuitton-electric-blue-silk-georgette-midi-dress-FODR29-U32620-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Zip-Up Wool-Silk Cady Dress",
    price: "14,500.00",
    Size: "36",
    image:
      "https://i.ibb.co/0YSF1f6/louis-vuitton-zip-up-wool-silk-cady-dress-FODR30-NQA900-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Metal Studs Metallized Leather Dress",
    price: "36,500.00",
    Size: "36",
    image:
      "https://i.ibb.co/fYjCTZ1/louis-vuitton-lv-x-yk-metal-studs-metallized-leather-dress-FOLD01-VQ4720-PM2-Front-view.webp",
    category: "dresses",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
    // women
  {
    title: "Monogram Workwear Short-Sleeved Shirt",
    price: "9,500.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/02z2tMM/louis-vuitton-monogram-workwear-short-sleeved-shirt-HOS46-WTZ0004-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Perforated Leather Short-Sleeved Shirt",
    price: "20,300.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/RSBgRRz/louis-vuitton-perforated-leather-short-sleeved-shirt-HPL10-WTV8321-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Summery Denim Shirt",
    price: "8,600.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/ZSZhnKz/louis-vuitton-monogram-summery-denim-shirt-HPS05-WZQ9815-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Cotton Blend Officer Shirt",
    price: "7,950.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/BgdRFS8/louis-vuitton-cotton-blend-officer-shirt-HPS20-WZO8321-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Infinity Dots Printed Zipped Shirt",
    price: "5,450.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/zf3qDwn/louis-vuitton-lv-x-yk-infinity-dots-printed-zipped-shirt-HOS30-WV29001-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Long-Sleeved Regular Shirt With Placed Graphic",
    price: "4,350.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/cwcvJX5/louis-vuitton-long-sleeved-regular-shirt-with-placed-graphic-HOS75-WUD7744-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Baseball Shirt",
    price: "5,600.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/C7wS17c/louis-vuitton-baseball-shirt-HOS83-WYN1900-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Multi Buttonholes Short-Sleeved Pyjama Shirt",
    price: "50,000.00",
    size: ["XS", "SO", "MO", "LO", "XL", "3L"],
    image:
      "https://i.ibb.co/R47MsGs/louis-vuitton-multi-buttonholes-short-sleeved-pyjama-shirt-HOS59-WV03-MU1-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Knotted Collar Long-Sleeved Shirt",
    price: "5,000.00",
    size: ["XS", "SO", "MO", "LO", "XL", "3L"],
    image:
      "https://i.ibb.co/wwvgvWk/louis-vuitton-knotted-collar-long-sleeved-shirt-HOS90-WV38518-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Knotted Collar Long-Sleeved Shirt",
    price: "5,000.00",
    size: ["SO", "MO", "LO", "XL", "3L"],
    image:
      "https://i.ibb.co/bBYJV1v/louis-vuitton-knotted-collar-long-sleeved-shirt-HOS90-WV38002-PM2-Front-view.webp",
    category: "shirts",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Technical Cotton Zipped Track Top",
    price: "10,400.00",
    size: ["SO", "MO", "LO", "4L"],
    image:
      "https://i.ibb.co/x78nz3T/louis-vuitton-technical-cotton-zipped-track-top-HPN20-WZ38920-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Cotton Short-Sleeved Crewneck",
    price: "5,200.00",
    size: ["SO", "MO", "LO", "XL", "3L", "4L"],
    image:
      "https://i.ibb.co/x14Hwbx/louis-vuitton-cotton-short-sleeved-crewneck-HPN30-WHA0-MU3-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Short-Sleeved Cotton Crewneck",
    price: "5,200.00",
    size: ["SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/B62TgsQ/louis-vuitton-short-sleeved-cotton-crewneck-HPN15-WHA0002-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Cashmere And Cotton Blend Short-Sleeved Polo",
    price: "5,450.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/7R8wCh6/louis-vuitton-cashmere-and-cotton-blend-short-sleeved-polo-HPN34-WY35900-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Cashmere And Cotton Blend Short-Sleeved Polo",
    price: "5,450.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/dGqdskH/louis-vuitton-cashmere-and-cotton-blend-short-sleeved-polo-HPN34-WY35906-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Zip-Through Cotton Hoodie",
    price: "9,200.00",
    size: ["XS", "SO", "MO", "LO", "XL", "3L"],
    image:
      "https://i.ibb.co/M2y6XKw/louis-vuitton-monogram-zip-through-cotton-hoodie-HPY33-WZA8-MU1-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Cashmere Mix Cardigan",
    price: "7,650.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/Z669vN9/louis-vuitton-monogram-cashmere-mix-cardigan-HON43-WR93918-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Monogram Faces Knitted Cardigan",
    price: "7,950.00",
    size: ["XS", "SO", "MO", "LO", "XL", "3L"],
    image:
      "https://i.ibb.co/NSkh3Yv/louis-vuitton-lv-x-yk-monogram-faces-knitted-cardigan-HON39-WZLW604-PM2-Front-view.png",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Reversible Light Bomber",
    price: "11,900.00",
    size: ["XS", "SO", "MO", "LO", "XL", "3L"],
    image:
      "https://i.ibb.co/CvwMFbN/louis-vuitton-monogram-reversible-light-bomber-HON40-WZLW900-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Hybrid Hoodie Denim Jacket",
    price: "10,700.00",
    size: ["XS", "SO", "MO"],
    image:
      "https://i.ibb.co/pXjSnbv/louis-vuitton-hybrid-hoodie-denim-jacket-HNY83-WIHN313-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Cotton Napolitana Jacket",
    price: "15,300.00",
    size: ["XS", "SO", "MO", "LO", "XL", "3L"],
    image:
      "https://i.ibb.co/YyrhHsq/louis-vuitton-monogram-cotton-napolitana-jacket-HPJ42-ELGY001-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Embroidered Signature Wool Pont Neuf Jacket",
    price: "14,700.00",
    size: "50",
    image:
      "https://i.ibb.co/fQCf6sd/louis-vuitton-embroidered-signature-wool-pont-neuf-jacket-HOJ41-E283653-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Damier Silk Blend Jacket",
    price: "15,300.00",
    size: "50",
    image:
      "https://i.ibb.co/N3kQDVy/louis-vuitton-ripstop-tailored-jacket-HPJ01-E220908-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Ripstop Tailored Jacket",
    price: "15,300.00",
    size: "50",
    image:
      "https://i.ibb.co/N3kQDVy/louis-vuitton-ripstop-tailored-jacket-HPJ01-E220908-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Shibori Napolitana Jacket",
    price: "15,800.00",
    size: "50",
    image:
      "https://i.ibb.co/djD6wKb/louis-vuitton-monogram-shibori-napolitana-jacket-HOJ80-EXF6739-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Strappy Single-Breasted Jacket",
    price: "19,700.00",
    size: "50",
    image:
      "https://i.ibb.co/6tQWdV2/louis-vuitton-strappy-single-breasted-jacket-HOJ65-EXG2-MU1-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Strappy Single-Breasted Jacket",
    price: "18,300.00",
    size: "50",
    image:
      "https://i.ibb.co/0fc2hPt/louis-vuitton-strappy-single-breasted-jacket-HOJ65-EOY9739-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Wrapped Martingale Jacket",
    price: "19,700.00",
    size: "50",
    image:
      "https://i.ibb.co/87KKJzX/louis-vuitton-wrapped-martingale-jacket-HOJ63-EEY2518-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Single-Breasted Pont Neuf Cutaway Jacket",
    price: "14,700.00",
    size: "50",
    image:
      "https://i.ibb.co/1XWLKC4/louis-vuitton-single-breasted-pont-neuf-cutaway-jacket-HPFJ6-ER58631-PM2-Front-view.webp",
    category: "jacket",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Denim Workwear Jacket",
    price: "13,500.00",
    size: "50",
    image:
      "https://i.ibb.co/cLb2F4V/louis-vuitton-monogram-denim-workwear-jacket-HPA05-WZO9920-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Workwear Denim Jacket",
    price: "14,100.00",
    size: "50",
    image:
      "https://i.ibb.co/VNjL6J7/louis-vuitton-workwear-denim-jacket-HPA46-WY38650-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Printed Nylon Windbreaker",
    price: "13,500.00",
    size: "50",
    image:
      "https://i.ibb.co/Sdk7dg7/louis-vuitton-printed-nylon-windbreaker-HPB10-WZS2321-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Leather And Knitted Wool Blouson",
    price: "14,100.00",
    size: "50",
    image:
      "https://i.ibb.co/R7nRB5t/louis-vuitton-leather-and-knitted-wool-blouson-HPN14-WVOR900-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Embroidered Faces Varsity Blouson",
    price: "30,000.00",
    size: "50",
    image:
      "https://i.ibb.co/0VKvtH4/louis-vuitton-lv-x-yk-embroidered-faces-varsity-blouson-HOL30-EVN6641-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Faces Zipped Fleece Blouson",
    price: "9,200.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/L9p5Dzg/louis-vuitton-lv-x-yk-faces-zipped-fleece-blouson-HOY35-WXY0-MU1-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK All Over Pumpkin Denim Blouson",
    price: "14,100.00",
    size: "50",
    image:
      "https://i.ibb.co/VWS5MSy/louis-vuitton-lv-x-yk-all-over-pumpkin-denim-blouson-HOA30-WYN3650-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Spray Denim Jacket",
    price: "10,700.00",
    size: "50",
    image:
      "https://i.ibb.co/v4dJ8sG/louis-vuitton-lv-spray-denim-jacket-HOA10-XU14-MU1-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Jacquard Camo Fleece Blouson",
    price: "9,500.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/SVHX4GC/louis-vuitton-jacquard-camo-fleece-blouson-HOY40-WU33-MU1-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Infinity Dots Fleece Blouson",
    price: "9,200.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/M9Sfwqc/louis-vuitton-lv-x-yk-infinity-dots-fleece-blouson-HOY38-WXX0904-PM2-Front-view.webp",
    category: "outerwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Bleached Denim Shorts",
    price: "5,750.00",
    size: "36",
    image:
      "https://i.ibb.co/vvqt3q7/louis-vuitton-bleached-denim-shorts-FPPA59-GM1001-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Frayed Hem Denim Mini Shorts",
    price: "5,750.00",
    size: "36",
    image:
      "https://i.ibb.co/Wc54d2C/louis-vuitton-frayed-hem-denim-mini-shorts-FPPA44-GM1610-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Painted Dots Pajama Pants",
    price: "8,850.00",
    size: "36",
    image:
      "https://i.ibb.co/qBSTz1q/louis-vuitton-lv-x-yk-painted-dots-pajama-pants-FOPT05-VD4900-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Stencil-effect Monogram Jogging Pants",
    price: "9,300.00",
    size: "38",
    image:
      "https://i.ibb.co/tbcz1JY/louis-vuitton-stencil-effect-monogram-jogging-pants-FIPA11-DFU001-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Chain Print Wide-Leg Pajama Pants",
    price: "7,600.00",
    size: "42",
    image:
      "https://i.ibb.co/JjspbTy/louis-vuitton-chain-print-wide-leg-pajama-pants-FOPT16-X97990-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Textured Silk Carrot Pants",
    price: "11,300.00",
    size: "42",
    image:
      "https://i.ibb.co/wMPtBVx/louis-vuitton-textured-silk-carrot-pants-FOPA91-VK6001-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Denim Carrot Pants",
    price: "7,950.00",
    size: "38",
    image:
      "https://i.ibb.co/hyrk9Wx/louis-vuitton-denim-carrot-pants-FOPX35-GM1610-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Satin Waistband Tailored Pants",
    price: "8,550.00",
    size: "36",
    image:
      "https://i.ibb.co/W3hrYxL/louis-vuitton-satin-waistband-tailored-pants-FPPX40-DVN900-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Bubble Damier Straight-Cut Pants",
    price: "7,950.00",
    size: "36",
    image:
      "https://i.ibb.co/R90Z1Y4/louis-vuitton-bubble-damier-straight-cut-pants-FPPX30-ACM900-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Square Neck Zip-Off Jumpsuit",
    price: "15,300.00",
    size: "36",
    image:
      "https://i.ibb.co/LpFNSjJ/louis-vuitton-square-neck-zip-off-jumpsuit-FPPX36-RD7900-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Printed Nylon Swim Shorts",
    price: "4,250.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/6wTmXCk/louis-vuitton-printed-nylon-swim-shorts-HPW03-WZP6332-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Printed Nylon Swim Shorts",
    price: "4,250.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/M8hjv2p/louis-vuitton-printed-nylon-swim-shorts-HPW02-WZP7920-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Signature Board Swimshorts",
    price: "3,750.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/TKXcGsj/louis-vuitton-signature-board-swimshorts-HNW11-WTB3405-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Nylon Swim Board Shorts",
    price: "3,100.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/pbKFBmX/louis-vuitton-monogram-nylon-swim-board-shorts-HJW52-WOSJ332-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Signature Board Swimshorts",
    price: "3,750.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/kXmSF7M/louis-vuitton-signature-board-swimshorts-HNW11-WTB3900-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "3D POCKET MONOGRAM BOARD SHORTS",
    price: "3,500.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/5spq7Qx/louis-vuitton-3d-pocket-monogram-board-shorts-HHW55-WOSJ631-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Monogram Faces Swimshorts",
    price: "4,250.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/8MwcK7p/louis-vuitton-lv-x-yk-monogram-faces-swimshorts-HOW30-WZNV604-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LVSE Signature Swim Board Shorts",
    price: "2,800.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/q96BZJL/louis-vuitton-lvse-signature-swim-board-shorts-HNW52-WOSJ645-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LVSE 3D Pocket Monogram Board Shorts",
    price: "3,050.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/qxp9Pf0/louis-vuitton-lvse-3d-pocket-monogram-board-shorts-HNW55-WOSJ645-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Bandana Board Swim Shorts",
    price: "4,350.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/TB6px6h/louis-vuitton-bandana-board-swim-shorts-HNW11-XN06401-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Accent Pillow Puffer Jacket",
    price: "19,700.00",
    size: "36",
    image:
      "https://i.ibb.co/g38WhFd/louis-vuitton-monogram-accent-pillow-puffer-jacket-FPOW30-RD7000-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Leather Accent Sleeveless Puffer Jacket",
    price: "25,600.00",
    size: "36",
    image:
      "https://i.ibb.co/s6qG78C/louis-vuitton-leather-accent-sleeveless-puffer-jacket-FPOW19-RD7210-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Long-Sleeved Pillow Puffer Jacket",
    price: "15,300.00",
    size: "38",
    image:
      "https://i.ibb.co/C8fpvxc/louis-vuitton-long-sleeved-pillow-puffer-jacket-FOOW21-E54900-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Metallic Sunset Mountain Puffer Jacket",
    price: "20,000.00",
    size: "36",
    image:
      "https://i.ibb.co/hfzpFMR/louis-vuitton-metallic-sunset-mountain-puffer-jacket-FMOW25-KW4401-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Sunset Mountain Sleeveless Puffer Jacket",
    price: "14,400.00",
    size: "36",
    image:
      "https://i.ibb.co/dM7YgJz/louis-vuitton-sunset-mountain-sleeveless-puffer-jacket-FMOW32-LR5401-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Metallic Monogram Flowers Reversible Puffer Jacket",
    price: "24,300.00",
    size: "36",
    image:
      "https://i.ibb.co/8MtkP4j/louis-vuitton-metallic-monogram-flowers-reversible-puffer-jacket-FNOW33-IV9960-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Louis Vuitton 2054 Heat Reactive Puffer",
    price: "24,500.00",
    size: "46",
    image:
      "https://i.ibb.co/ccSxz8w/louis-vuitton-louis-vuitton-2054-heat-reactive-puffer-HMB23-WI64901-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Padded Puffer Cape",
    price: "21,500.00",
    size: "34",
    image:
      "https://i.ibb.co/SXTvhP8/louis-vuitton-padded-puffer-cape-FPOW20-RD7210-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Short Pillow Puffer Wrap Coat",
    price: "23,700.00",
    size: "38",
    image:
      "https://i.ibb.co/BqXDW0f/louis-vuitton-short-pillow-puffer-wrap-coat-FNOW29-E54900-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Glossy Long Puffer Coat",
    price: "23,100.00",
    size: "36",
    image:
      "https://i.ibb.co/KsBdhK0/louis-vuitton-glossy-long-puffer-coat-FMOW06-H32900-PM2-Front-view.webp",
    category: "puffer-jackets",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Frill Blouse",
    price: "6,200.00",
    size: "36",
    image:
      "https://i.ibb.co/BKywBNd/louis-vuitton-frill-blouse-FHBL13-AQV000-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Fil Coupé Sleeveless Shirt",
    price: "9,150.00",
    size: "36",
    image:
      "https://i.ibb.co/J7qxwp6/louis-vuitton-monogram-fil-coup-sleeveless-shirt-FPBL28-UM7000-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Technical Jersey Zip-Up Sports Bra",
    price: "5,850.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/d4SFP8j/louis-vuitton-technical-jersey-zip-up-sports-bra-FPJT03-G72010-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Stretch Jersey Boxy Bateau Crop Top",
    price: "5,500.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/KyJqcYs/louis-vuitton-stretch-jersey-boxy-bateau-crop-top-FPJT04-Y05001-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Tiles Boxy Shirt",
    price: "9,150.00",
    size: "36",
    image:
      "https://i.ibb.co/C0CBYB2/louis-vuitton-monogram-tiles-boxy-shirt-FPBL28-DYN033-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Tiles Cape Blouse",
    price: "9,150.00",
    size: "36",
    image:
      "https://i.ibb.co/Kbdj9S1/louis-vuitton-monogram-tiles-cape-blouse-FPBL17-DYD033-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Tiles Blouse",
    price: "9,150.00",
    size: "36",
    image:
      "https://i.ibb.co/wMDSMX8/louis-vuitton-monogram-tiles-blouse-FPBL01-DYD033-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Python Monogram Oversized Zipper Shirt",
    price: "9,800.00",
    size: "36",
    image:
      "https://i.ibb.co/qNRfpqr/louis-vuitton-python-monogram-oversized-zipper-shirt-FOTO39148004-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Eyelet Cotton Drill Shirt",
    price: "11,000.00",
    size: "36",
    image:
      "https://i.ibb.co/xJwpLXG/louis-vuitton-eyelet-cotton-drill-shirt-FPBL13-BT9614-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Calfskin Tent Top",
    price: "44,000.00",
    size: "36",
    image:
      "https://i.ibb.co/MghyWSx/louis-vuitton-calfskin-tent-top-FOLB10-NJ3900-PM2-Front-view.webp",
    category: "tops",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Stripe Accent Monogram Pleated Skirt",
    price: "17,700.00",
    size: "38",
    image:
      "https://i.ibb.co/GncwHbY/louis-vuitton-stripe-accent-monogram-pleated-skirt-FOSX45-TR0130-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "3D Monogram Asymmetrical Pleat Midi Skirt",
    price: "17,700.00",
    size: "36",
    image:
      "https://i.ibb.co/j9KxwVm/louis-vuitton-3d-monogram-asymmetrical-pleat-midi-skirt-FPSX35-ADD001-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Technical Jersey Zip-Up Skirt",
    price: "7,950.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/Xj7m1Ny/louis-vuitton-technical-jersey-zip-up-skirt-FPJS01-G72010-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Bubble Damier Paperbag Mini Skirt",
    price: "15,900.00",
    size: "36",
    image:
      "https://i.ibb.co/LvvM6dQ/louis-vuitton-bubble-damier-paperbag-mini-skirt-FPSK30-ACM900-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Tiered Snap Button Skirt",
    price: "17,700.00",
    size: "36",
    image:
      "https://i.ibb.co/QKpyqYc/louis-vuitton-tiered-snap-button-skirt-FPSK29-IGL017-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Scallop Detail A-Line Mini Skirt",
    price: "16,500.00",
    size: "36",
    image:
      "https://i.ibb.co/7Jw916z/louis-vuitton-scallop-detail-a-line-mini-skirt-FPSK28-AAR900-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Vintage Monogram Mini Skirt",
    price: "10,300.00",
    size: "36",
    image:
      "https://i.ibb.co/7Wbx6dM/louis-vuitton-vintage-monogram-mini-skirt-FPSK36-ACG004-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Flower Tile Midi Skirt",
    price: "15,300.00",
    size: "36",
    image:
      "https://i.ibb.co/FBdTDSG/louis-vuitton-monogram-flower-tile-midi-skirt-FPSK12-DYD610-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Flower Tile Pocket Mini Skirt",
    price: "9,750.00",
    size: "36",
    image:
      "https://i.ibb.co/SwHV9f8/louis-vuitton-monogram-flower-tile-pocket-mini-skirt-FPSK23-FDM610-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Pleated Jersey Maxi Skirt",
    price: "16,600.00",
    size: "36",
    image:
      "https://i.ibb.co/Kwp91Rh/louis-vuitton-pleated-jersey-maxi-skirt-FPSX07-Y26900-PM2-Front-view.webp",
    category: "skirt",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Silk Short",
    price: "7,350.00",
    size: "50",
    image:
      "https://i.ibb.co/LRS8WqY/louis-vuitton-monogram-silk-short-HPP34-WZ49920-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Crepe Shorts",
    price: "6,700.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/Sn9TNbw/louis-vuitton-monogram-cotton-shorts-HPY34-WZA8-MU1-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Ripstop Cargo Short",
    price: "5,200.00",
    size: "50",
    image:
      "https://i.ibb.co/pLfJfkP/louis-vuitton-ripstop-cargo-short-HPP01-WYH7900-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Cotton Shorts",
    price: "6,700.00",
    size: "50",
    image:
      "https://i.ibb.co/pLfJfkP/louis-vuitton-ripstop-cargo-short-HPP01-WYH7900-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Monogram Faces Knitted Shorts",
    price: "6,050.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/jkkb0Ww/louis-vuitton-lv-x-yk-monogram-faces-knitted-shorts-HON29-WZLW604-PM2-Front-view.png",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Denim Pants",
    price: "8,600.00",
    size: "36",
    image:
      "https://i.ibb.co/PcBrr6y/louis-vuitton-monogram-denim-pants-HPD15-WZO9920-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Workwear Denim Carpenter Pants",
    price: "11,000.00",
    size: "34",
    image:
      "https://i.ibb.co/jwDzN43/louis-vuitton-workwear-denim-carpenter-pants-HOD45-WY38650-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Denim Carpenter Shorts",
    price: "7,350.00",
    size: "33",
    image:
      "https://i.ibb.co/sW8gKkx/louis-vuitton-denim-carpenter-shorts-HPD47-WY3865-S-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Workwear Denim Carpenter Pants",
    price: "10,700.00",
    size: "32",
    image:
      "https://i.ibb.co/DKM5ByP/louis-vuitton-monogram-workwear-denim-carpenter-pants-HOD45-WTZ0004-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Slim Stretch Denim Pants",
    price: "3,250.00",
    size: "27",
    image:
      "https://i.ibb.co/wK0wKqw/louis-vuitton-slim-stretch-denim-pants-HID70-WDKN650-PM2-Front-view.webp",
    category: "pants",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Graphic Sequin Turtleneck Sweater",
    price: "20,000.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/G7DhFdb/louis-vuitton-graphic-sequin-turtleneck-sweater-FNKL74-TQ7108-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Mixed Stripes Knit Top",
    price: "6,800.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/4FGY3rh/louis-vuitton-mixed-stripes-knit-top-FPKS01167-R90-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Infinity Dots Cardigan",
    price: "14,500.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/Wtr0v3L/louis-vuitton-lv-x-yk-infinity-dots-cardigan-FOKC09-YB7001-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Painted Dots Knit Top",
    price: "10,100.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/LtW2RcR/louis-vuitton-lv-x-yk-painted-dots-knit-top-FOKS09-YB8001-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Infinity Dots Knit Crop Top",
    price: "8,850.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/2q2Hc7R/louis-vuitton-lv-x-yk-infinity-dots-knit-crop-top-FOKS07-YC1900-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Long Knitted Coat",
    price: "19,700.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/wJqmJVF/louis-vuitton-long-knitted-coat-FPKX14-AMO226-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Compact Knit Cropped Cardigan",
    price: "10,300.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/c8Pdpn1/louis-vuitton-compact-knit-cropped-cardigan-FPKC17-AMO002-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Chain Shawl Collar Cardigan",
    price: "17,700.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/58hVxwS/louis-vuitton-lv-chain-shawl-collar-cardigan-FPKC16-AMK001-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Ribbed Crop Top",
    price: "5,500.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/HpbFfnx/louis-vuitton-ribbed-crop-top-FPKW19-N93001-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Beaded Trim Compact Knit Cropped Cardigan",
    price: "28,300.00",
    size: ["XS", "SO", "MO", "LO", "XL"],
    image:
      "https://i.ibb.co/qp1Fj0y/louis-vuitton-beaded-trim-compact-knit-cropped-cardigan-FPKC20-AMP035-PM2-Front-view.webp",
    category: "knitwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Flap Pocket Hooded Wrap Coat",
    price: "23,300.00",
    size: "36",
    image:
      "https://i.ibb.co/6mbTbmk/louis-vuitton-flap-pocket-hooded-wrap-coat-FOCO46-RO1631-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Hooded Double-Breasted Coat",
    price: "27,100.00",
    size: "36",
    image:
      "https://i.ibb.co/bQdLxLb/louis-vuitton-hooded-double-breasted-coat-FPCX14-QWE711-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Sleeveless Leather Strip Mink Coat",
    price: "101,000.00",
    size: "36",
    image:
      "https://i.ibb.co/rxsnSvp/louis-vuitton-sleeveless-leather-strip-mink-coat-FPLJ11-DIG900-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "3D Monogram Double-Breasted Wrap Coat",
    price: "25,600.00",
    size: "36",
    image:
      "https://i.ibb.co/cDBH2yb/louis-vuitton-3d-monogram-double-breasted-wrap-coat-FPCO10-AIG141-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Signature Short Hooded Wrap Coat",
    price: "25,100.00",
    size: "36",
    image:
      "https://i.ibb.co/jMr9tPH/louis-vuitton-signature-short-hooded-wrap-coat-FPCO38-RO1631-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Wool Hopsack Belted Coat",
    price: "30,000.00",
    size: "36",
    image:
      "https://i.ibb.co/QmrVG4G/louis-vuitton-wool-hopsack-belted-coat-FPCO21-IGL017-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Double-Breasted Mohair Toile Coat",
    price: "23,900.00",
    size: "36",
    image:
      "https://i.ibb.co/ftfPckR/louis-vuitton-double-breasted-mohair-toile-coat-FPCO16-DVN900-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Belted Pinstripe Topstitch Coat",
    price: "37,000.00",
    size: "36",
    image:
      "https://i.ibb.co/nCDqzyy/louis-vuitton-belted-pinstripe-topstitch-coat-FPCO31-FMH702-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Removable Collar Double Face Coat",
    price: "28,300.00",
    size: "36",
    image:
      "https://i.ibb.co/S0XRgwJ/louis-vuitton-removable-collar-double-face-coat-FPCO29-AIG141-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Anchor Button Lapel Coat",
    price: "27,700.00",
    size: "36",
    image:
      "https://i.ibb.co/DM1RhBY/louis-vuitton-anchor-button-lapel-coat-FPCO02-Q14614-PM2-Front-view.webp",
    category: "coat",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Jacquard Bikini Top",
    price: "3,050.00",
    size: "36",
    image:
      "https://i.ibb.co/Mnn2n7d/louis-vuitton-monogram-jacquard-bikini-top-FPSW25-UN7001-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Jacquard Sporty Bikini Top",
    price: "3,500.00",
    size: "36",
    image:
      "https://i.ibb.co/c35vXC1/louis-vuitton-monogram-jacquard-sporty-bikini-top-FPSW15-UN7900-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK Painted Dots One-Piece Swimsuit",
    price: "4,100.00",
    size: "36",
    image:
      "https://i.ibb.co/d59qcD9/louis-vuitton-lv-x-yk-painted-dots-one-piece-swimsuit-FOSW32-VY8900-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Sprayed Monogram Bikini Top",
    price: "3,150.00",
    size: "36",
    image:
      "https://i.ibb.co/3S4R5fD/louis-vuitton-sprayed-monogram-bikini-top-FOSW52-W05620-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Cut-Out Balconette Bikini Top",
    price: "3,500.00",
    size: "36",
    image:
      "https://i.ibb.co/gFvTcH2/louis-vuitton-cut-out-balconette-bikini-top-FOSW11-HRN900-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Jacquard One-Piece Swimsuit",
    price: "3,050.00",
    size: "34",
    image:
      "https://i.ibb.co/g6pz7s3/louis-vuitton-monogram-jacquard-one-piece-swimsuit-FPSW17-UN7001-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Graphic Monogram Bikini Top",
    price: "2,500.00",
    size: "34",
    image:
      "https://i.ibb.co/Fq0qZKq/louis-vuitton-graphic-monogram-bikini-top-FOSW19-UUM900-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Twist Front Bikini Top",
    price: "3,700.00",
    size: "36",
    image:
      "https://i.ibb.co/XVsLqq2/louis-vuitton-twist-front-bikini-top-FPSW39-DLM900-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Twist Detail One-Piece Swimsuit",
    price: "4,000.00",
    size: "36",
    image:
      "https://i.ibb.co/pzvfM4p/louis-vuitton-twist-detail-one-piece-swimsuit-FPSW34-DLM900-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Flower Tile One-Piece Swimsuit",
    price: "4,600.00",
    size: "36",
    image:
      "https://i.ibb.co/0GjNCVC/louis-vuitton-monogram-flower-tile-one-piece-swimsuit-FPSW32-END610-PM2-Front-view.webp",
    category: "swimwear",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Victorine Wallet",
    price: "2,550.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/ynyzByZ/louis-vuitton-victorine-wallet-M62360-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Rosalie Coin Purse",
    price: "1,800.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/FYXP15z/louis-vuitton-rosalie-coin-purse-M62361-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Rosalie Coin Purse",
    price: "2,150.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/FKSyQQt/louis-vuitton-rosalie-coin-purse-M81455-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Key Pouch",
    price: "1,450.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/7gtmNQW/louis-vuitton-key-pouch-M62650-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Sarah Wallet",
    price: "3,400.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/zmNQKjj/louis-vuitton-sarah-wallet-M80726-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Zippy Wallet",
    price: "3,450.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/xjQHLkV/louis-vuitton-zippy-wallet-M42616-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Emilie Wallet",
    price: "2,600.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/PWVBDvq/louis-vuitton-emilie-wallet-M60697-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Toiletry Pouch On Chain",
    price: "8,200.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/55NGBZR/louis-vuitton-toiletry-pouch-on-chain-M81412-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Mini Pochette Accessoires",
    price: "3,850.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/WxskqFv/louis-vuitton-mini-pochette-accessoires-M80732-PM2-Front-view.webp",
    category: "wallets-for-women",
  },
  {
    title: "Nano Speedy",
    price: "8,500.00",
    Materials: "Monogram",
    image:
      "https://i.ibb.co/SB4G6cd/louis-vuitton-nano-speedy-M81085-PM2-Front-view.webp",
    category: "wallets-for-women",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Chain Necklace",
    price: "5,350.00",
    image:
      "https://i.ibb.co/n7RkYNp/louis-vuitton-monogram-chain-necklace-M01190-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Award Tie Pin",
    price: "1,900.00",
    image:
      "https://i.ibb.co/4m6QKs9/louis-vuitton-lv-award-tie-pin-M00913-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Chain Bracelet",
    price: "2,900.00",
    image:
      "https://i.ibb.co/VLQVCVP/louis-vuitton-monogram-chain-bracelet-M00686-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Instinct Set of 2 Rings",
    price: "2,100.00",
    image:
      "https://i.ibb.co/V2kVy7J/louis-vuitton-lv-instinct-set-of-2-rings-M00514-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Catch Cufflinks",
    price: "2,150.00",
    image:
      "https://i.ibb.co/GnV3kYh/louis-vuitton-lv-catch-cufflinks-M80188-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Loop It Bracelet",
    price: "1,700.00",
    size: "19",
    image:
      "https://i.ibb.co/vVhNFDj/louis-vuitton-loop-it-bracelet-M6780-E-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Initiales Tie Clip",
    price: "1,600.00",
    image:
      "https://i.ibb.co/t8JkjfP/louis-vuitton-lv-initiales-tie-clip-M61981-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram charms necklace",
    price: "2,450.00",
    image:
      "https://i.ibb.co/WFr7fM3/louis-vuitton-monogram-charms-necklace-M62485-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Hang It Bracelet",
    price: "1,900.00",
    image:
      "https://i.ibb.co/5xPsJLv/louis-vuitton-hang-it-bracelet-M8294-E-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Monogram Chain Bracelet",
    price: "3,400.00",
    image:
      "https://i.ibb.co/801Dbrn/louis-vuitton-monogram-chain-bracelet-M1042-M-PM2-Front-view.webp",
    category: "all-fashion-jewellery",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Empreinte Ear Cuff",
    price: "22,000.00",
    image:
      "https://i.ibb.co/RjTYnVW/louis-vuitton-empreinte-ear-cuff-pink-gold-and-diamonds-per-unit-Q06109-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Blooming Earrings",
    price: "1,700.00",
    image:
      "https://i.ibb.co/kQcnH9v/louis-vuitton-blooming-earrings-M64859-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Louisette Earrings",
    price: "2,050.00",
    image:
      "https://i.ibb.co/6PJccXg/louis-vuitton-louisette-earrings-M80267-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Louise Hoop GM Earrings",
    price: "3,050.00",
    image:
      "https://i.ibb.co/7gbqpvS/louis-vuitton-louise-hoop-gm-earrings-M64288-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Essential V Stud Earrings",
    price: "1,700.00",
    image:
      "https://i.ibb.co/nBmkH6t/louis-vuitton-essential-v-stud-earrings-M63208-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Essential V hoops",
    price: "2,000.00",
    image:
      "https://i.ibb.co/BZVmc7m/louis-vuitton-essential-v-hoops-M61088-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Essential V Stud Earrings",
    price: "1,700.00",
    image:
      "https://i.ibb.co/g97r4W6/louis-vuitton-star-blossom-stud-white-gold-and-diamonds-per-unit-Q96966-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Volt One Stud",
    price: "7,950.00",
    image:
      "https://i.ibb.co/fMtfv5D/louis-vuitton-lv-volt-one-stud-pink-gold-and-diamond-per-unit-Q96975-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Color Blossom BB Star Ear Studs",
    price: "17,900.00",
    image:
      "https://i.ibb.co/gtDJ759/louis-vuitton-color-blossom-bb-star-ear-studs-pink-gold-pink-mother-of-pearl-and-diamonds-Q96667-PM2.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Idylle Blossom Long Earrings",
    price: "22,200.00",
    image:
      "https://i.ibb.co/Vv6ftcV/louis-vuitton-idylle-blossom-long-earrings-3-golds-and-diamonds-Q96413-PM2-Front-view.webp",
    category: "earrings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Essential V Necklace",
    price: "2,300.00",
    image:
      "https://i.ibb.co/JKqpysR/louis-vuitton-essential-v-necklace-M00857-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Louise By Night Necklace",
    price: "2,700.00",
    image:
      "https://i.ibb.co/Ky4ySVx/louis-vuitton-louise-by-night-necklace-M00759-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Iconic Necklace",
    price: "2,450.00",
    image:
      "https://i.ibb.co/z5T47B1/louis-vuitton-lv-iconic-necklace-M00596-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Petit Louis Necklace",
    price: "2,300.00",
    image:
      "https://i.ibb.co/VpCX4mx/louis-vuitton-petit-louis-necklace-M00368-PM2-Front-view.webp",
    category: "necklaces",
  },
  {
    title: "LV Iconic Enamel Necklace",
    price: "2,300.00",
    image:
      "https://i.ibb.co/ZXs3KPH/louis-vuitton-lv-iconic-enamel-necklace-M01215-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Chain-It Necklace",
    price: "5,950.00",
    image:
      "https://i.ibb.co/nqG3nV9/louis-vuitton-lv-chain-it-necklace-M01343-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Eclipse Pearls Necklace",
    price: "2,750.00",
    image:
      "https://i.ibb.co/0cTLz2W/louis-vuitton-lv-eclipse-pearls-necklace-M01239-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Stellar Necklace",
    price: "4,650.00",
    image:
      "https://i.ibb.co/XxqBQzG/louis-vuitton-lv-stellar-necklace-M01224-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Crown Necklace",
    price: "7,200.00",
    image:
      "https://i.ibb.co/Kw7zFPM/louis-vuitton-lv-crown-necklace-M01280-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "My LV Chain Necklace",
    price: "4,050.00",
    image:
      "https://i.ibb.co/RyY3YyN/louis-vuitton-my-lv-chain-necklace-M01123-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV x YK LV Iconic Infinity Dots Necklace",
    price: "2,900.00",
    image:
      "https://i.ibb.co/JFbc36G/louis-vuitton-lv-x-yk-lv-iconic-infinity-dots-necklace-M01081-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Twiggy Necklace",
    price: "2,450.00",
    image:
      "https://i.ibb.co/5F6dPPf/louis-vuitton-lv-twiggy-necklace-M00980-PM2-Front-view.webp",
    category: "necklaces",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Buddy Bracelet",
    price: "1,900.00",
    image:
      "https://i.ibb.co/KFkgnfZ/louis-vuitton-lv-buddy-bracelet-M1056-Z-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Vivienne Kick Flip Bracelet",
    price: "2,150.00",
    image:
      "https://i.ibb.co/KNmbh72/louis-vuitton-vivienne-kick-flip-bracelet-M1051-Z-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Crew Bracelet",
    price: "2,150.00",
    image:
      "https://i.ibb.co/ygn6Bg7/louis-vuitton-lv-crew-bracelet-M1020-Z-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Crew Bracelet",
    price: "2,150.00",
    image:
      "https://i.ibb.co/MnfJTVs/louis-vuitton-lv-crew-bracelet-M1019-Z-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Bloom Bracelet",
    price: "1,800.00",
    image:
      "https://i.ibb.co/rM2fwrB/louis-vuitton-lv-bloom-bracelet-M8142-Z-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Contouring Bracelet",
    price: "1,800.00",
    image:
      "https://i.ibb.co/6g00cqM/louis-vuitton-lv-contouring-bracelet-M8150-E-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Keep It Bracelet",
    price: "1,200.00",
    image:
      "https://i.ibb.co/yhqRjJk/louis-vuitton-keep-it-bracelet-M8137-E-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Nano Monogram bracelet",
    price: "1,350.00",
    image:
      "https://i.ibb.co/tPrMBbQ/louis-vuitton-nano-monogram-bracelet-M8112-E-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Keep It Twice bracelet",
    price: "1,850.00",
    image:
      "https://i.ibb.co/dp5svvp/louis-vuitton-keep-it-twice-bracelet-M8109-E-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Iconic Bracelet",
    price: "1,800.00",
    image:
      "https://i.ibb.co/mhjZzM1/louis-vuitton-lv-iconic-bracelet-M8088-F-PM2-Front-view.webp",
    category: "bracelet",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Eclipse Pearls Rings",
    price: "2,150.00",
    image:
      "https://i.ibb.co/wsDKCff/louis-vuitton-lv-eclipse-pearls-rings-M1080-M-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Stellar Ring",
    price: "1,900.00",
    image:
      "https://i.ibb.co/m0B0Zny/louis-vuitton-lv-stellar-ring-M0937-S-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Twiggy Ring",
    price: "2,150.00",
    image:
      "https://i.ibb.co/1rdzFWT/louis-vuitton-lv-twiggy-ring-M0914-S-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Twiggy Ring",
    price: "1,700.00",
    image:
      "https://i.ibb.co/GtvVvcX/louis-vuitton-lv-twiggy-ring-M0906-S-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Stellar Ring",
    price: "2,150.00",
    image:
      "https://i.ibb.co/g6wZmzq/louis-vuitton-lv-stellar-ring-M0905-S-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Eclipse Bague",
    price: "1,700.00",
    image:
      "https://i.ibb.co/vZdF0jj/louis-vuitton-lv-eclipse-bague-M00768-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "My LV Chain Ring",
    price: "1,900.00",
    image:
      "https://i.ibb.co/2N8HTVv/louis-vuitton-my-lv-chain-ring-M0979-M-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Nanogram Ring",
    price: "1,850.00",
    image:
      "https://i.ibb.co/k4RCJzK/louis-vuitton-nanogram-ring-M00211-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "Louisette Ring",
    price: "1,850.00",
    image:
      "https://i.ibb.co/x8462GN/louis-vuitton-louisette-ring-M0949-S-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
  {
    title: "LV Futura Ring",
    price: "2,150.00",
    image:
      "https://i.ibb.co/1MTqYYF/louis-vuitton-lv-futura-ring-MP355-S-PM2-Front-view.webp",
    category: "rings",
    color: ["red", "black", "blue"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
  },
];
