export const data = [
  {
    title: "FOSFO FLOW- Women's Down Puffer Jacket - AK10055",
    price: "600",
    image: "https://i.postimg.cc/T2j9LhZ6/F-FOSFOFlow-Sable-Face-1-720x.webp",
    color: ["red", "black", "blue"],
    category: "jacket",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO FLOW- Women's Down Puffer Jacket - AK10055",
    price: "600",
    image:
      "https://i.postimg.cc/1zPRzC6P/F-FOSFOFlow-Bleupale-Face-5-720x.webp",
    color: ["red", "black", "red"],
    category: "jacket",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO FLOW- Women's Down Puffer Jacket - AK10055",
    price: "600",
    image: "https://i.postimg.cc/9X4DKkYN/F-FOSFOFlow-Noir-Face-4-720x.webp",
    color: ["red", "black", "red"],
    category: "jacket",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO FLOW- Women's Down Puffer Jacket - AK10055",
    price: "600",
    image: "https://i.postimg.cc/fTfDr7pr/F-FOSFOCourt-Citron-Face-2-720x.webp",
    color: ["red", "black", "red"],
    category: "jacket",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO SHORT- Women's Down Puffer Jacket - AK10051",
    price: "350",
    image:
      "https://i.postimg.cc/hjTH7cq5/F-FOSFOCourt-vertpin-Face-1-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "jacket",
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO SHORT- Women's Down Puffer Jacket - AK10051",
    price: "350",
    image:
      "https://i.postimg.cc/B6TVnpTW/032521-AUDVIK-ECOMM-FOSFO-COURT-BLEUMINUIT-0772-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "jacket",
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO SHORT - Women's down puffer jacket - AK10051",
    price: "350",
    image:
      "https://i.postimg.cc/KzWR47xN/FOSFO-COURT-BLEU-PALE-AUDVIK47382-720x.webp",
    category: "jacket",
    color: ["red", "black", "red"],
    type: "styleguide1",
  },
  {
    title: "FOSFO SHORT - Women's down puffer jacket - AK10051",
    price: "350",
    image:
      "https://i.postimg.cc/4Nkp5ZR1/032521-AUDVIK-ECOMM-FOSFO-COURT-NOIR-1403-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "jacket",
    quantity: "14",
    type: "styleguide1",
  },
  {
    title:
      "https://i.postimg.cc/G2vm3Wgc/032521-AUDVIK-ECOMM-FOSFO-COURT-ORANGE-1372-720x.webpRT",
    price: "350",
    image: "",
    category: "jacket",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO SHORT - Women's down puffer jacket - AK10051",
    price: "350",
    category: "jacket",
    image:
      "https://i.postimg.cc/YCzDDZYG/F-fosfocourt-taupe-1-1-scaled-720x-1.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO SHORT - Women's down puffer jacket - AK10051",
    price: "350",
    category: "jacket",
    image: "https://i.postimg.cc/Fz2pbJgb/F-FOSFOLong-Vertpin-Face-1-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO SHORT - Women's down puffer jacket - AK10051",
    price: "350",
    image: "https://i.postimg.cc/htL1PmtH/F-FOSFOLong-Citron-Face-4-720x.webp",
    color: ["red", "black", "red"],
    category: "jacket",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide1",
  },
  {
    title: "FOSFO LONG - Women's down puffer jacket - AK10050",
    price: "400",
    image:
      "https://i.postimg.cc/05dh6zH1/032521-AUDVIK-ECOMM-FOSFO-LONG-BLEUMINUIT-1105-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "punjabi",
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO LONG - Women's down puffer jacket - AK10050",
    price: "400",
    image:
      "https://i.postimg.cc/T2zJnxhj/FOSFO-LONG-BLEU-PALE-AUDVIK47452-5-1-720x.webp",
    color: ["red", "black", "red"],
    category: "punjabi",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO LONG - Women's down puffer jacket - AK10050",
    price: "400",
    image:
      "https://i.postimg.cc/QtsrFw1j/032521-AUDVIK-ECOMM-FOSFO-LONG-ORANGE-1086-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "punjabi",
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO LONG - Women's down puffer jacket - AK10050",
    price: "400",
    image:
      "https://i.postimg.cc/3RLb3cZS/032521-AUDVIK-ECOMM-FOSFO-LONG-NOIR-1462-1-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "punjabi",
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO LONG - Women's down puffer jacket - AK10050",
    price: "400",
    image:
      "https://i.postimg.cc/gjQSZLQ3/032521-AUDVIK-ECOMM-FOSFO-LONG-TAUPE-1039-1-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "punjabi",
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO LONG - Women's down puffer jacket - AK10050",
    price: "400",
    image:
      "https://i.postimg.cc/wBgWLpf4/FOSFO-XL-BLEU-POUDRE-AUDVIK47257-720x.webp",
    color: ["red", "black", "red"],
    category: "punjabi",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO MAXI - Women's down puffer jacket - AK10052",
    price: "650",
    image: "https://i.postimg.cc/wv8gz304/FOSFO-XL-NOIR-AUDVIK47365-720x.webp",
    color: ["red", "black", "red"],
    category: "punjabi",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO MAXI - Women's down puffer jacket - AK10052",
    price: "650",
    image:
      "https://i.postimg.cc/tRzp0qPD/FOSFO-XL-TAUPE-AUDVIK47309-5-720x.webp",
    color: ["red", "black", "red"],
    category: "punjabi",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO MAXI - Women's down puffer jacket - AK10052",
    price: "650",
    image:
      "https://i.postimg.cc/Zq3zw448/032521-AUDVIK-ECOMM-FOSFO-PULLOVER-BLEUPALE-1452-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "punjabi",
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO Women's Sleeveless Puffer Vest - AK10058",
    price: "250",
    image:
      "https://i.postimg.cc/1X74Sw4h/F-FOSFOsansmanches-Noir-Face-1-720x.webp",
    color: ["red", "black", "red"],
    category: "punjabi",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO Women's Sleeveless Puffer Vest - AK10058",
    price: "250",
    image:
      "https://i.postimg.cc/c4KLYKrC/F-FOSFOsansmanches-Bleupale-Cote-2-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO Women's Sleeveless Puffer Vest - AK10058",
    price: "250",
    image:
      "https://i.postimg.cc/SNWNVBfb/F-FOSFOsansmanches-Sable-Face-1-720x.webp",
    color: ["red", "black", "red"],
    category: "punjabi",
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO PLUS SIZE- Women’s down puffer jacket - AK10050X",
    price: "250",
    image:
      "https://i.postimg.cc/xjXPkRyz/FOSFO-LONG-BLEU-TPLUS-AUDVIK48042-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    category: "punjabi",
    quantity: "14",
    type: "styleguide2",
  },
  {
    title: "FOSFO PLUS SIZE- Women’s down puffer jacket - AK10050X",
    price: "250",
    image:
      "https://i.postimg.cc/QMNQjkdV/FOSFO-LONG-NOIR-TPLUS-AUDVIK47981-3-720x.webp",
    color: ["red", "black", "red"],
    size: ["s", "m", "l", "xl"],
    quantity: "14",
    category: "punjabi",
    type: "styleguide2",
  },
];
